import type { Metadata } from "next";
import "./globals.css";
import Layout from "@/Layout/Layout";
import ReactQueryProvider from "@/Layout/ReactQueryProvider";
import { FontBase } from "@/utils/fonts/FontBase";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`dark ${FontBase().className}`}>
        <Layout>
          <ReactQueryProvider>{children}</ReactQueryProvider>
        </Layout>
      </body>
    </html>
  );
}
