import type { Metadata } from "next";
import "./globals.css";
import Providers from "./Providers";
import { getCookie } from "@/core/models/cookie/token-cookie";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    const accessToken = await getCookie("accessToken");
  return (
    <html lang="en" dir="rtl">
      <body className="dark bg-base">
        <Providers accessToken={accessToken}>{children}</Providers>
      </body>
    </html>
  );
}
